name: Bug Report
description: Please let us know if you're facing any problems, errors, or unexpected behavior.
assignees: techtanic
title: "[Bug]: "
labels: ["Type: Bug", "Status: TBC"]
body:
  - type: markdown  
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please describe the issue you encountered and what you expected to happen.
        You can also attach image by highlighting this area and dragging the files in.
      placeholder: Describe your experience.
    validations:
      required: true

  - type: dropdown
    id: enroller
    attributes:
      label: Enroller
      description: Which Enroller caused this issue?
      options:
        - GUI
        - CLI
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux-Distro
        - Mac-OS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Upload Log file `duce.log`
      description: |
        Drag and drop `duce.log` from the application folder into this text area.**

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/techtanic/Discounted-Udemy-Course-Enroller/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I am using the latest available version.
          required: true
